### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by elpiel** [Stremio/stremio-service#3]
- [x] add `LICENSE` file #33 
- [x] Update `Readme.md` #33 
- [x] Update `Cargo.toml` (if our license differs from the current `MIT` license) #33 
- [x] Add `LICENSE` file to the release zip in the github actions (macos, windows) #33
